### ISSUE TITLE
Can you please help me to create this shape?

### ISSUE THREAD

**Issue by irfan78773** [Monntay/CustomTabBarShape#1]
I am attaching the image can you please help me to create this shape?

<img width="632" alt="screen shot 2018-12-12 at 4 20 06 pm" src="https://user-images.githubusercontent.com/45169805/49865035-dd04e580-fe29-11e8-90ef-75515fee78b0.png">

**Comment by Monntay** [comment]
Like mentioned in the article I did the curve by try and error.

 How to create the eye middle Button can be found in the repo. The three upper Buttons are straight forward I guess.
