### ISSUE TITLE
Buttons and TableView Not interacting in CutsomTabBarShape

### ISSUE THREAD

**Issue by osamainam777** [Monntay/CustomTabBarShape#3]
I added buttons and TableViews inside the a ViewController than added it inside the customTabBar but there is an issue that not item inside tabController is interacting. I press button and try to scroll the tableViews but nothing is interacting with it. 
Can you help? 
Looking forward to hear from you
Thanks

**Comment by tradefunmain** [comment]
Add this to your Tab Bar Class

```swift
override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        guard !clipsToBounds && !isHidden && alpha > 0 else { return nil }
        for member in subviews.reversed() {
            let subPoint = member.convert(point, from: self)
            guard let result = member.hitTest(subPoint, with: event) else { continue }
            return result
        }
        return nil
    }
```

**Comment by osamainam777** [comment]
Works like charm. Thanks a bunch!!!!!
